// exception handling
// error handling  


// try {

// } catch (error) {

// }

// throw new Error("");

// custome eror 


// validation error 
// run error 
//  // syntax error 
// logical error 
// declaration error 

// try {
//  for(let i=0;i<0;i++){
//     console.log(i)
//  }   
// } catch (error) {
//    console.log("error",error); 
// }

// let a = 30;
// b = 0;
// if (a / b == 0) {
//     console.log("throw new error")
//     throw new Error(`${a} is not divisible by ${b}`);
// }
// else {
//     console.log(`${a} is divisible by ${b}`);
// }

// console.log("object")


// if (18 !== b) {
//     console.log(`age is not equel to  user age  ${b}`)
// }



// if (18 <= b) {
//     console.log(`you are valiadate person`);
// }
// else{
//     console.log(`you are valiadate person`);

// }





// try {
//     const res = fetch("http://localhost:3000/api");
//     console.log(res)
// } catch (error) {
//     console.log(error);
// }

// const res = fetch("http://localhost:3000/api")
// .then(data => data.json())
// .catch(error => {
//     console.log(error.message)
//     console.log(error.name)

// }
// );